name: .NET CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout of the repo
      - uses: actions/checkout@v3

      # Setup .NET 9
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # Restore packages
      - name: Restore dependencies
        run: dotnet restore

      # Build solution
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Test 
       - name: Run tests with coverage
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

       - name: Report coverage
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.9
        with:
            reports: "**/TestResults/**/coverage.cobertura.xml"
            targetdir: "coveragereport"
            reporttypes: "Html"

       - name: Upload coverage report artifact
        uses: actions/upload-artifact@v3
        with:
            name: coverage-report
            path: coveragereport

      # Update database (disabled: no DB cloud in CI)
      # - name: Update Database
      #   run: dotnet ef database update --project SkillSwap.Infrastructure --startup-project SkillSwap.Api
      #   env:
      #     SKILLSWAP_DB_CONNECTION: ${{ secrets.SKILLSWAP_DB_CONNECTION }}
