name: Auto-approve PR if author is me

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve PR
        uses: peter-evans/approve-pull-request@v3
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          message: 'Auto-approved because I am the king ehm I mean the repo owner'
        if: github.actor == 'FrankOfTheScience'
